export const baseURL = 'http://localhost:4000/'
export const USER_ACTION = {
    LOGIN: 'USER_LOGIN',
    LOGOUT: 'USER_LOGOUT',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAIL: 'USER_LOGIN_FAIL',
    REGISTER: 'USER_REGISTER',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAIL: 'USER_REGISTER_FAIL'
}