export const baseURL = 'http://localhost:4000/'
export const USER_ACTION = {
    LOGIN: 'USER_LOGIN',
    LOGOUT: 'USER_LOGOUT',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAIL: 'USER_LOGIN_FAIL',
    REGISTER: 'USER_REGISTER',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAIL: 'USER_REGISTER_FAIL',
    LOGIN_FACEBOOK: 'USER_LOGIN_FACEBOOK',
    LOGIN_FACEBOOK_SUCCESS: 'USER_LOGIN_FACEBOOK_SUCCESS',
    LOGIN_FACEBOOK_FAIL: 'USER_LOGIN_FACEBOOK_FAIL',
    LOGIN_GOOGLE: 'USER_LOGIN_GOOGLE',
    LOGIN_GOOGLE_SUCCESS: 'USER_LOGIN_GOOGLE_SUCCESS',
    LOGIN_GOOGLE_FAIL: 'USER_LOGIN_GOOGLE_FAIL',
}